[package]
name = "glasshaus"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
clap_complete = "4.5.66"
clap_mangen = "0.2.31"
tokio = { version = "1.49.0", features = ["full"] }

[env]
RUSTFLAGS="-Awarnings"
